openapi: 3.0.0
info:
  title: Task Management API
  version: 1.0.0
  description: API for managing users, projects, tasks, and comments
paths:
  /users:
    get:
      summary: Get all users
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /projects:
    get:
      summary: Get all projects
      responses:
        '200':
          description: List of projects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
  /tasks:
    get:
      summary: Get all tasks
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
  /comments:
    get:
      summary: Get all comments
      responses:
        '200':
          description: List of comments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        password:
          type: string
        createdAt:
          type: string
          format: date-time
    UserProject:
      type: object
      properties:
        userId:
          type: string
        projectId:
          type: string
        role:
          type: string
          enum: [owner, member]
    Project:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        createdAt:
          type: string
          format: date-time
    Task:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        status:
          type: string
          enum: [pending, in-progress, completed, cancelled]
        createdAt:
          type: string
          format: date-time
        lastUpdated:
          type: string
          format: date-time
        dueDate:
          type: string
          format: date-time
        assignedTo:
          type: string
        projectId:
          type: string
    Comment:
      type: object
      properties:
        id:
          type: string
        body:
          type: string
        taskId:
          type: string
        userId:
          type: string
        createdAt:
          type: string
          format: date-time
