@baseUrl = http://localhost:3000

### Docs
GET {{baseUrl}}/docs

### User

### Create a new user
GET {{baseUrl}}/users
### Get user by ID
GET {{baseUrl}}/users/132c98ca-0a8d-4d96-b8c6-cc59fec7a326
### Create a new user
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "Alfonso",
    "email": "alfonso@gmail.com",
    "password": "password"
}
### Update user by ID
PUT {{baseUrl}}/users/132c98ca-0a8d-4d96-b8c6-cc59fec7a326
Content-Type: application/json

{
    "name": "Alfonso Perez",
    "password": "newpassword"
}
### Delete user by ID
DELETE {{baseUrl}}/users/132c98ca-0a8d-4d96-b8c6-cc59fec7a326

---

### Project

### Create a new project
POST {{baseUrl}}/projects
Content-Type: application/json

{
    "name": "New Project",
    "description": "This is a new project"
}
### Get all projects
GET {{baseUrl}}/projects
### Get project by ID
GET {{baseUrl}}/projects/28e62bd7-3bcb-4e21-93a4-1522a4d299c1
### Update project by ID
PUT {{baseUrl}}/projects/28e62bd7-3bcb-4e21-93a4-1522a4d299c1
Content-Type: application/json

{
    "name": "Updated Project",
    "description": "New description"
}
### Delete project by ID
DELETE {{baseUrl}}/projects/28e62bd7-3bcb-4e21-93a4-1522a4d299c1

---

### Task

### Create a new task
POST {{baseUrl}}/tasks
Content-Type: application/json

{
    "title": "New Task",
    "description": "This is a new task",
    "status": "pending",
    "assigned_to": "132c98ca-0a8d-4d96-b8c6-cc59fec7a326",
    "project_id": "28e62bd7-3bcb-4e21-93a4-1522a4d299c1"
}
### Get all tasks
GET {{baseUrl}}/tasks
### Get task by ID
GET {{baseUrl}}/tasks/4d5bc448-8dcb-43ba-893c-366a7c9e0763
### Update task by ID
PUT {{baseUrl}}/tasks/4d5bc448-8dcb-43ba-893c-366a7c9e0763
Content-Type: application/json

{
    "title": "Updated Task",
    "status": "in_progress"
}
### Update task by ID, failing case
PUT {{baseUrl}}/tasks/4d5bc448-8dcb-43ba-893c-366a7c9e0763
Content-Type: application/json

{
    "title": "Updated Task",
    "status": "pending"
}
### Delete task by ID
DELETE {{baseUrl}}/tasks/4d5bc448-8dcb-43ba-893c-366a7c9e0763

---

### Comment

### Create a new comment
POST {{baseUrl}}/comments
Content-Type: application/json

{
    "body": "Test comment",
    "task_id": "4d5bc448-8dcb-43ba-893c-366a7c9e0763",
    "author_id": "132c98ca-0a8d-4d96-b8c6-cc59fec7a326"
}
### Get all comments
GET {{baseUrl}}/comments
### Get comment by ID
GET {{baseUrl}}/comments/a62af9f3-5d82-4f9b-9558-2d2dbfecfaf6
### Update comment by ID
PUT {{baseUrl}}/comments/a62af9f3-5d82-4f9b-9558-2d2dbfecfaf6
Content-Type: application/json

{
    "body": "Updated comment"
}
### Delete comment by ID
DELETE {{baseUrl}}/comments/a62af9f3-5d82-4f9b-9558-2d2dbfecfaf6

### User-Project Association

### Create a new user-project association
POST {{baseUrl}}/usersProjects
Content-Type: application/json

{
    "userId": "132c98ca-0a8d-4d96-b8c6-cc59fec7a326",
    "projectId": "28e62bd7-3bcb-4e21-93a4-1522a4d299c1"
}
### Get all user-project associations
GET {{baseUrl}}/usersProjects
### Get user-project association by ID
GET {{baseUrl}}/usersProjects/7462e856-542d-46c2-b417-b8d5d737e9a6
### Get user-project association by project&user id
GET {{baseUrl}}/usersProjects/28e62bd7-3bcb-4e21-93a4-1522a4d299c1/132c98ca-0a8d-4d96-b8c6-cc59fec7a326
### Update user-project association by ID
PUT {{baseUrl}}/usersProjects/7462e856-542d-46c2-b417-b8d5d737e9a6
Content-Type: application/json

{
    "role": "owner"
}
### Update user-project association by project&user id
PUT {{baseUrl}}/usersProjects/28e62bd7-3bcb-4e21-93a4-1522a4d299c1/132c98ca-0a8d-4d96-b8c6-cc59fec7a326
Content-Type: application/json

{
    "role": "owner"
}
### Delete user-project association by ID
DELETE {{baseUrl}}/usersProjects/7462e856-542d-46c2-b417-b8d5d737e9a6
### Delete user-project association by project&user id
DELETE {{baseUrl}}/usersProjects/28e62bd7-3bcb-4e21-93a4-1522a4d299c1/132c98ca-0a8d-4d96-b8c6-cc59fec7a326